"use client";

// Real, comprehensive Users Guide content — reused directly from the
// same verified source already used for CHS_USERS_GUIDE.docx, so both
// the downloadable document and this in-app page always say the same thing.
export default function GuideContent() {
  return (
    <div className="text-sm text-gray-600 leading-relaxed space-y-2">
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">1. What Is CHS?</h2>
      <p>CHS (Complete Housing Solutions) is a real estate platform covering the full property journey — buying, renting, leasing, short-stay bookings, and property sales — currently focused on Kaduna State, Nigeria. Unlike a simple listings site, CHS is an active facilitator: it verifies documents and identities, holds funds in escrow until conditions are genuinely met, and provides a real dispute-resolution process if something goes wrong between two parties.</p>
      <p>CHS is built around one core rule that shapes everything else in this guide: every transaction started on CHS should be completed on CHS. That&apos;s what makes the escrow protection, the verification, and the dispute process actually mean something — none of it works if a deal moves off-platform halfway through.</p>
      <p>The platform serves many different kinds of people, each with their own dashboard and tools:</p>
      <ul className="list-disc pl-5 space-y-1 mb-2">
        <li>Buyers — searching to purchase, rent, lease, or hire a property</li>
        <li>Tenants — already renting, or about to start renting, through CHS</li>
        <li>Property Owners — listing a property to sell, rent, lease, or hire out</li>
        <li>Agents — marketing properties and earning referral commission</li>
        <li>Property Managers — managing properties professionally on behalf of owners</li>
        <li>Commercial Developers — selling estates, offering instalment or investment plans</li>
        <li>Vendors — selling building materials or services through the CHS Marketplace</li>
        <li>Artisans — skilled tradespeople (plumbers, electricians, painters, and more) who take on real maintenance jobs</li>
        <li>CHS Admin Team — the staff who verify, approve, and keep the platform running safely</li>
      </ul>
      <p>One person can hold more than one of these roles on the same account — for example, someone can be both a Property Owner and a Tenant. See &quot;Linking additional roles&quot; in the next section.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">2. Getting Started</h2>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">2.1 Creating your account</h3>
      <p>Go to the Register page and choose the role that best describes why you&apos;re joining. You&apos;ll be asked for your name, phone number, email, and a password, plus some role-specific details:</p>
      <ul className="list-disc pl-5 space-y-1 mb-2">
        <li>Agent — your operating LGAs, years of real estate experience, and any professional association/membership ID you hold</li>
        <li>Property Manager — your profession, professional registration number (if any), the states you operate in, and an upload of your professional certificate or licence</li>
        <li>Commercial Developer — your company and project details</li>
      </ul>
      <p>Every account also needs a valid means of identification uploaded during registration or shortly after — this is what unlocks the platform&apos;s trust features later (see 2.3).</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">2.2 Approval and verification status</h3>
      <p>New accounts start in a pending state while the CHS team confirms the details you provided are genuine. You&apos;ll get a real notification the moment a decision is made — approved accounts can use the platform immediately; if something needs fixing, you&apos;ll be told what and can update your details.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">2.3 Verifying your identity</h3>
      <p>Two separate, real verification steps exist on CHS, and they unlock different things:</p>
      <p><strong className="text-chs-charcoal">Valid ID Verification —</strong> uploading a real, valid means of ID (National ID, driver&apos;s licence, international passport, or voter&apos;s card). This is what&apos;s checked before certain high-trust actions are allowed — for example, listing a property under Urgent &amp; Emergency Sale (see section 6) requires this.</p>
      <p><strong className="text-chs-charcoal">Liveness / Face Verification —</strong> a genuine, real-time photo capture done directly on your device — never an uploaded or automated photo. This confirms the person using the account is a real person matching the account, and CHS staff review each capture directly rather than relying on any automated pass/fail.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">2.4 Logging in, and biometric login</h3>
      <p>Log in with your phone/email and password as normal. If your device supports it, you can also set up biometric login — Face ID, fingerprint, or your device&apos;s own screen lock — from your Profile page, so you don&apos;t need to re-type your password every time. This uses your device&apos;s own secure hardware; CHS never sees or stores your actual fingerprint or face data.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">2.5 Linking additional roles to one account</h3>
      <p>If you already have a CHS account and want to add another role to it — for example, you registered as a Buyer but now also want to list a property as an Owner, or you&apos;re a registered professional (Agent, Property Manager, Artisan) wanting to add a second professional role — use &quot;Link Account&quot; rather than registering a brand-new account. This keeps your one real identity, one wallet, and one login working across every role you hold.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">2.6 Terms &amp; Conditions, and your first-time guide</h3>
      <p>Before reaching your dashboard for the first time, you&apos;ll be asked to genuinely scroll through and accept the real CHS Terms &amp; Conditions — the checkbox only unlocks once you&apos;ve reached the bottom. Right after that, you&apos;ll see a short, role-specific quick-start guide (just for your own role — not the whole of this document) which you can dismiss once read; a permanent link to the fuller guide stays available afterward from your Profile page.</p>
      <p>The Terms carry a version number (Version 6 adds term 37, on records and timestamps). When they change, everyone is asked to read and accept the new version once, on their next visit — you are shown what is new so you are not re-reading blind. Every acceptance is recorded permanently with the version number and the exact time, so there is always a clear record of what you agreed to. Version 2 added term 36 on refunds (see 4.11). Version 3 rewrote term 11 so hotels, lodges, shortlets and event centres are booked request-first (see 4.5). Version 4 (October 2026) added the rule that every payment is made through the CHS Wallet only, the wallet protections (transaction PIN, limits, a 24-hour pause on received or card-funded money, device checks, Freeze, fraud reports), the inspection cost rule, the release of sale money, and the Rent to Own changes.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">3. Your CHS Wallet</h2>
      <p>Every CHS account gets a real wallet automatically, the moment your profile is created. It&apos;s the one place all your CHS money moves through — funding, spending, withdrawing, and now, sending to other users directly.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">3.1 Funding your wallet</h3>
      <p>From the Wallet page, enter an amount and tap &quot;Continue to pay.&quot; This opens a real, secure Paystack payment window — card, bank transfer, or USSD. Once the payment genuinely completes, your wallet balance updates automatically (usually within a few seconds).</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">3.2 Withdrawing to your bank account</h3>
      <p>CHS deliberately allows only one linked bank account per wallet, for security — this is enforced at the database level, not just a setting you could work around. To withdraw, enter the amount from your Wallet page; funds are sent to your one linked account. If you need to change your linked account, that goes through a real, separate approval flow rather than an instant swap, to protect against someone else quietly redirecting your future withdrawals.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">3.3 Sending money to another CHS user</h3>
      <p>From the Wallet page, tap &quot;Send to another CHS user,&quot; enter their phone number or email, confirm you&apos;ve found the right person by name, enter an amount, and confirm. The transfer is instant and moves real money between the two wallets — you cannot send to yourself, and a transfer is blocked if your balance is insufficient or your wallet is currently frozen.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">3.4 Frozen wallets</h3>
      <p>CHS reserves the right to freeze a wallet pending a genuine investigation into suspected fraud or a policy violation. A frozen wallet can still be viewed, but withdrawals and transfers are blocked until the matter is resolved. If your wallet is frozen, you&apos;ll see this clearly on your Wallet page.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">3.5 Maintenance Reserve (Property Owners)</h3>
      <p>Your Maintenance Reserve is a real, separate balance for funding repairs. You can move money into it directly from your Main Wallet at any time — useful when a real maintenance bill is larger than what&apos;s already set aside. When you confirm a maintenance job complete, payment is drawn from your Maintenance Reserve first, and only from your Main Wallet for any real shortfall. Unused Maintenance Reserve funds can be withdrawn back to your Main Wallet at any time, with no approval required.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">3.6 Held funds from a property sale</h3>
      <p>If you sell a property, your real net proceeds appear in your wallet the moment the buyer pays — but as a held balance you can see, not yet withdraw. This is a genuine protection for the buyer: your funds only move into your spendable Main Wallet once CHS confirms the real, physical legal documents (Deed of Assignment, Certificate of Occupancy, and everything else required) have genuinely been transferred to them. There&apos;s nothing further for you to do to trigger this — CHS coordinates the real handover and releases the funds once it&apos;s confirmed complete.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">4. Finding a Property (Buyers &amp; Tenants)</h2>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.1 Searching and filtering</h3>
      <p>The homepage shows real, active, CHS-verified listings. Use the Rent / Sale / Shortlet tabs to narrow by purpose, and the search tool to filter by state, LGA, area, price range, property type, and minimum bedrooms.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.2 Saved Properties and Saved Searches</h3>
      <p>Tap the save icon on any listing to keep it in your &quot;Saved&quot; page for later. Separately, you can save a whole search — your exact filter combination (purpose, location, price range, bedrooms) — so you don&apos;t have to re-enter it every time; a saved search is also what powers a future vacancy-alert match if a new listing fits it.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.3 Making an offer or rental application</h3>
      <p>On a for-sale property, use &quot;Make an Offer&quot; to propose a price directly to the owner. On a rental, submit a rental application — CHS staff screen it first before it&apos;s passed to the owner for their final decision; the owner never sees an application CHS hasn&apos;t reviewed.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.4 Once your offer is accepted — paying for a property</h3>
      <p>When the owner accepts your offer, you&apos;ll see a real, transparent breakdown before paying anything: the accepted price, your commission (shown as both the percentage and the real Naira amount), and the combined total due — charged in one single payment, never as two separate charges. The seller likewise sees, in advance, the real net amount they&apos;ll receive after their own commission.</p>
      <p>Payment can only go through once CHS has verified every real legal document required for that property — Certificate of Occupancy, Deed of Assignment, Survey Plan, Governor&apos;s Consent, Tax Clearance Certificate, Sale Agreement, and Building Plan Approval where a real structure exists. If verification is still in progress, you&apos;ll see this clearly instead of a payment button, and you&apos;ll be notified the moment it&apos;s ready.</p>
      <p>Once you pay, the seller&apos;s proceeds are held — visible to them, but not withdrawable — until CHS confirms the real, physical legal documents have genuinely been transferred to you. This protects you as the buyer: the seller cannot access the money until you have real, complete legal ownership.</p>
      <p>If the documents have not been delivered by the deadline shown on your payment, you can request a refund from the same property page — see 4.11 for exactly what you get back.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.5 Shortlet bookings</h3>
      <p>Hotels, lodges, shortlets and event centres are booked in four steps. (1) Choose your dates on the calendar and send a request — <b>nothing is charged</b>. (2) CHS passes your request to the host, who confirms the dates are free. (3) You are notified and have a short window to pay from your CHS Wallet — 6 hours for a stay more than 3 days away, 2 hours for a stay in 1 to 3 days, 20 minutes for a stay today. Your payment is held in escrow. (4) When you arrive, tick the short arrival checklist on your booking — that you are in, the property is as described and each listed facility is present and working. That releases the payment to the host at once, and sends your message to the host and to CHS. If you do not respond it is released automatically 24 hours after check-in; if something is wrong, report a problem and the payment stays held. For a stay starting within 3 days, your wallet must already hold the full amount when you send the request; for a stay today you also tell the host roughly when you will arrive. If the host can&apos;t take you or doesn&apos;t reply, or you don&apos;t pay in time, the request lapses and you pay nothing. You can follow every step, and pay, from My Bookings. Everything goes through CHS: your request is passed to the host by CHS, and messages on a booking are reviewed by CHS before delivery until you have paid — phone numbers and emails are blocked, and the host never sees your phone number. You&apos;ll be asked for real guest details (name, phone, valid ID) before you can send a request. Once booked, use the real in-app messaging on your booking to reach your host directly — hosts may keep their identity private from guests, but CHS always knows who they are, and can step in directly if a host doesn&apos;t respond.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.6 Rent-to-Own</h3>
      <p>Some sale listings offer a rent-to-own path — paying a monthly amount that counts toward eventually owning the property outright, alongside a minimum deposit and a set number of years. Where available, this is shown directly on the property&apos;s listing page with the real monthly amount, the percentage that counts toward ownership, and the minimum deposit required.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.7 Talk to an Agent (Concierge)</h3>
      <p>If you&apos;d rather just describe what you&apos;re looking for in your own words instead of using the search filters, use &quot;Property request&quot; (in the bottom navigation) — type it out, or use your device&apos;s voice input. This is a real request that lands directly with the CHS team, who will search and follow up with you personally — a genuinely faster path when your requirements are specific or you&apos;re not sure exactly what to search for.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.8 Urgent &amp; Emergency Sale listings</h3>
      <p>Some for-sale properties are marked 🚨 Urgent Sale — a genuinely real, discounted, time-boxed sale from an owner who needs to sell fast (relocation, a medical situation, or another urgent financial need). These are shown with the real original price struck through next to the real discounted price, plus the actual deadline the owner needs to sell by. If you&apos;re interested, these listings show a direct CHS hotline number for faster processing than standard in-app messaging.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.9 A few quick questions when booking an inspection</h3>
      <p>When you book an inspection, you&apos;ll be asked three short questions — your timeline, whether your funds/deposit are ready, and whether you&apos;re the actual decision-maker. This never blocks your booking or costs anything extra — it simply helps the owner prioritize their own time fairly among genuinely ready buyers and tenants. Real, genuine attendance at inspections you book also matters here — it&apos;s one of the strongest real signals of serious interest.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.10 Once you&apos;re a tenant — your rent countdown and non-renewal notice</h3>
      <p>Once you move into a real tenancy, your dashboard shows a real, live day-count to your next rent due date — updated daily, not just a plain date range. If you don&apos;t plan to renew, please give notice at least 90 real days before your lease ends; your dashboard highlights this window as it approaches, with a real button to notify your landlord. Notice given later than 90 days is still recorded and sent, honestly noted as later than requested rather than refused.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">4.11 If the other side doesn&apos;t deliver — your refund</h3>
      <p>Because your money is held in escrow, it has not reached the other side. If a seller, landlord, host or vendor fails to do what they agreed, you can get your money back. This applies to every tenant, buyer and guest and is written into term 36 of the Terms &amp; Conditions.</p>
      <p><strong>What you get back:</strong> the full price you paid, <em>plus</em> CHS&apos;s own commission from you, <em>less</em> one deduction only — a real bank processing fee that CHS&apos;s payment provider already charged and cannot recover. The fee is 1.5% of CHS&apos;s commission from you plus ₦100, and never more than ₦2,000, however large the deal. Example: if CHS&apos;s commission from you was ₦100,000, the fee is ₦1,600, and you receive the full price plus ₦98,400. CHS also cancels the commission it would have charged the other side. The refund goes to your CHS Wallet and you are told the exact amount and fee.</p>
      <p><strong>When it opens:</strong> for a sale, once the document-delivery window has passed with the legal transfer unconfirmed; for rent, once the grace period has passed with no clean move-in report; for marketplace goods and for shortlet or hire bookings, once CHS has reviewed what went wrong. A host who declines your request at the start refunds you in full with nothing deducted.</p>
      <p><strong>How to ask:</strong> for a sale, use the &quot;Request refund &amp; cancel this deal&quot; button on the property page once the deadline has passed. For a shortlet or hire booking, cancel from My Bookings under the stated cancellation policy, or contact CHS if a host fails to honour a confirmed booking. For rent and marketplace purchases, contact CHS support with the property or order reference and the team will review and process it. A real reason is always recorded.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">5. Listing and Managing Property (Owners)</h2>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.1 Listing a property</h3>
      <p>From your Owner dashboard, use &quot;List a property&quot; to add a new listing — photos, location, price, purpose (rent/sale/shortlet), bedrooms, and any special terms (rent-to-own, house rules). A new listing starts unverified and isn&apos;t publicly visible until CHS confirms it.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.2 Getting verified</h3>
      <p>CHS reviews every new listing before it goes live — this is what makes &quot;CHS Verified&quot; mean something to a real buyer or tenant. You&apos;ll be notified the moment a decision is made, and everyone who&apos;d already expressed interest in the listing is notified too, the moment it goes live.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.2a Legal documents required to list a Sale property</h3>
      <p>Listing a property under Sale requires uploading real soft copies of the legal documents needed to genuinely transfer ownership under Nigerian law: Certificate of Occupancy, Deed of Assignment, Survey Plan, Governor&apos;s Consent, Tax Clearance Certificate, and Sale Agreement — plus Building Plan Approval if the property has a real structure on it (not required for raw land). CHS verifies each document independently. A buyer&apos;s payment cannot proceed until every required document for your property is confirmed verified.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.2b When a buyer&apos;s offer is accepted</h3>
      <p>Tap &quot;Offer Accepted — Proceed to Payment&quot; to accept a real offer — this is the actual next step for the buyer, not just a status change. You can also decline with an optional message, which the buyer receives directly. Once the buyer pays, your real proceeds appear in your wallet, held until CHS confirms the physical legal documents have genuinely been transferred to the buyer — see &quot;Your CHS Wallet&quot; above for how this hold works.</p>
      <p>If the documents are not delivered by the deadline, the buyer can request a refund and the deal is reversed: only that deal&apos;s share is removed from your held balance (your other held amounts are untouched), CHS&apos;s commission from you on it is cancelled, and your property is listed as available again. The same applies to a landlord whose tenant&apos;s grace period passes with no clean move-in report, a host who fails to honour a confirmed booking, and a vendor who does not deliver — see term 36. Delivering on time protects your payout.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.3 Promoting a listing</h3>
      <p>There are two separate ways to get extra visibility for a listing, and you can pick either:</p>
      <h4 className="text-xs font-bold text-chs-red mt-2 mb-1">Fixed Boost</h4>
      <p>A one-off, paid tier — 7-Day Boost, 30-Day Featured, or 90-Day Premium — debited directly from your wallet at time of purchase. Good for a single, time-limited push.</p>
      <h4 className="text-xs font-bold text-chs-red mt-2 mb-1">Credits — read this before you buy</h4>
      <p>Buy a reusable pool of promotion credits (₦400 each), or subscribe to a monthly package (Classic, Premium, Elite, or Signature) which includes bonus credits. Here is exactly how consumption works, in plain terms:</p>
      <ul className="list-disc pl-5 space-y-1 mb-2">
        <li>Your credits are ONE shared balance across every listing you own — not split up per listing.</li>
        <li>Each listing you turn ON is charged separately, every real day it stays on, all from that same one balance.</li>
        <li>If you turn on 3 listings at once, you pay for all 3 that day — there is no fixed daily limit on the whole account; your real total simply depends on how many listings you keep active and each one&apos;s own real cost.</li>
        <li>Turn any listing OFF any day for free — you are never charged for a day it was off.</li>
        <li>The daily cost for a specific listing depends on its real location and size — the exact number is always shown on the promote screen before you buy or turn anything on.</li>
      </ul>
      <p>Each promoted listing is also assigned a real ranking — both a category (A through D) and a literal position (e.g. &quot;#3 of Top 10&quot;), based on how it compares to other promoted listings in the same real local market — not a fixed national price line, so a smaller market isn&apos;t unfairly outranked by a bigger one. A higher position reflects relatively higher spend within that comparison group; it is not a separate purchase on top of your credits.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.4 Urgent &amp; Emergency Sale — activating it</h3>
      <p>From your Owner dashboard, tap &quot;🚨 Urgent Sale&quot; on a for-sale listing. Three real requirements must be met first: the listing must already be CHS Verified, your own identity must be ID-verified, and you&apos;ll need to set a real original price (higher than your current listed price — this becomes the genuine &quot;before&quot; price buyers see) and a real deadline. The moment it activates, the CHS team is notified immediately to help fast-track buyer interest, and it automatically switches back to a normal listing once the deadline passes unless you renew it.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.5 House Rules</h3>
      <p>For a rental property, you can upload a House Rules document that a tenant must acknowledge as part of their tenancy — a real, documented agreement both sides can refer back to.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">5.6 Delegating management to a Property Manager</h3>
      <p>If you&apos;d rather not handle day-to-day management yourself, you can delegate a property to a registered Property Manager. Once delegated, maintenance requests and certain approvals route to the manager instead of you directly — and this can be reversed (management termination) if needed.</p>
            <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">5A. No hidden prices: what every listing must show</h2>
      <p>Every listing on CHS, whether for sale, rent, lease, hire or a marketplace product or service, must show its real price, its location, a street address, at least five photos, at least one video, a short description and a contact phone number before it can go live. The contact number is kept private for CHS and the owner or agent; it is not shown publicly, so that every conversation stays on CHS where it is protected. The form will not submit until each item is filled in, and the database refuses to approve a listing that is missing any of them, so there is no way around it. Listings that tell people to &quot;DM&quot;, inbox, call or message for the price are refused with a message asking for the real price. A service must show a starting price. When a live listing&apos;s price changes, the earlier price and the date appear on the listing, so a price cannot quietly change. Owners see exactly what is missing on any listing that is not live yet, with a link to add it. Reviewers see the same list plus warning signs: a new or unverified owner, a possible duplicate listing, copied photos (a photo that closely matches one in another owner&apos;s listing, even if resized), and a price far from similar listings.</p>
      <p><strong className="text-chs-charcoal">Staying current, reports and trust signals.</strong> For a property for sale, rent or lease, the owner confirms every 30 days that it is still available, with one tap on the dashboard. CHS reminds you at 25 days; a listing that is not confirmed is hidden from the public after 30 days and returns the moment you confirm. Anyone signed in can report a listing from its page (hidden or wrong price, fake or copied, already taken, scam behaviour); the owner is not told who reported. Reviewers can dismiss a report, tell the owner to fix it, or take the listing down, and the person who reported is told the outcome. Each live listing shows plain trust signals: price shown upfront, whether the owner&apos;s ID is verified, the year the owner joined, and how recently availability was confirmed. See Terms 39 and 40.</p>
<h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">6. Agents</h2>
      <p>Every registered agent gets a unique referral code (e.g. CHS-AG-0024), automatically attached to every property link generated from their dashboard.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">6.1 How the referral link works</h3>
      <p>A referral link always opens the property directly on CHS — never on your personal page or any third-party site — so CHS can verify the transaction and calculate your commission accurately, and so the buyer or tenant always transacts through CHS&apos;s real protections regardless of where they first saw the link.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">6.2 Where you can share it</h3>
      <p>Anywhere you already have an audience — your Facebook page, WhatsApp status, Instagram bio, a physical flyer with a short link, and so on. Sharing the link doesn&apos;t move any part of the transaction off CHS; it only brings the visitor to CHS.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">6.3 How commission is credited</h3>
      <p>If someone clicks your link, browses, and eventually completes a transaction on that property, CHS automatically attributes the deal to your code and credits your commission — no manual claim or extra step required from you.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">7. Property Managers</h2>
      <p>As a registered Property Manager, owners can delegate specific properties to you for day-to-day handling. Delegated properties route their maintenance and certain approval flows to you directly. Delegation can be reversed by the owner at any time (management termination), which hands the relevant responsibilities back to the owner.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">8. Commercial Developers</h2>
      <p>As a registered Developer, your application is reviewed by CHS before your projects (estates, instalment or investment plans) go live on the platform. Once approved, you can list and manage development projects through your Developer dashboard.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">9. Vendors — The CHS Marketplace</h2>
      <p>The Marketplace connects property owners, tenants, and managers with real vendors of building materials and services. To become a vendor, use &quot;Become a Vendor&quot; — your registration is reviewed and verified by CHS before your listings go live, the same trust standard applied everywhere else on the platform.</p>
      <p>As a vendor, real referral fees may apply on deals connected through the Marketplace, tracked automatically and visible from your vendor dashboard.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">10. Artisans</h2>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">10.1 Becoming an artisan</h3>
      <p>Use &quot;Become an Artisan&quot; to register. Select every real trade you genuinely have — you&apos;re not limited to one:</p>
      <ul className="list-disc pl-5 space-y-1 mb-2">
        <li>Painter, Plumber, Electrician, Carpenter, Bricklayer/Mason, Tiler</li>
        <li>Welder/Metal fabricator, Roofer, POP/Ceiling installer</li>
        <li>AC/Refrigeration technician, Generator technician, Aluminium/Glazier</li>
        <li>Interior decorator, Landscaper/Gardener, Borehole driller</li>
        <li>Professional cleaner, Fumigation/Pest control, or Other</li>
      </ul>
      <p>You&apos;ll also declare your real years of experience, any certification body, and your equipment level (basic hand tools, power tools, or professional-grade) — claims about equipment can be backed with a real photo and receipt, since CHS verifies what&apos;s claimed rather than taking it on trust alone.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">10.2 Getting verified</h3>
      <p>Your registration is reviewed by CHS before you can quote on real jobs. Once verified, you&apos;re notified and can start quoting on maintenance jobs matching your trade and location.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">10.3 Fault reports and quotes</h3>
      <p>When a tenant or owner reports a maintenance fault, it&apos;s routed to the right decision-maker first — the property manager if that property&apos;s management is genuinely delegated, the owner otherwise. Real quotations from artisans are ranked by a transparent formula weighted toward rating and reliability first, experience second, and equipment third. For any property under full CHS management, maintenance work is offered first and exclusively to verified CHS Maintenance Agents.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">10.4 Disputes on a completed job</h3>
      <p>Either you or the client can raise a genuine, two-sided dispute about a completed job if something went wrong — CHS reviews these directly rather than automatically siding with either party.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">11. Engaging CHS for a Professional Service</h2>
      <p>Beyond listings, CHS itself offers direct professional services — Full Property Management, Sale Negotiation, Construction Monitoring, Project Management, and Renovation. Use &quot;Engage CHS&quot; to submit a real request describing what you need; the CHS team will respond directly, and each service carries its own specific terms and fee schedule reviewed with you before work begins.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">11.1 Construction Roadmap</h3>
      <p>If you&apos;re considering Construction Monitoring or Full Construction/Project Management, you can unlock a real Construction Roadmap for your specific building type (1–4 bedroom bungalow, or 3–5 bedroom duplex) for a one-time fee — real room-by-room quantities, a real Kaduna permits checklist, a real milestone payment plan, and an estimated cost range. This fee is fully credited toward your real project cost if you proceed with CHS for construction — it&apos;s never money lost if you go ahead. The cost range shown is a general, sourced market indication, clearly labeled as such, until CHS&apos;s own verified rates are available for your specific configuration.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">12. Disputes and Community Feedback</h2>
      <p>If a real disagreement arises between two parties on a transaction, either side can raise a dispute — CHS&apos;s internal resolution process is the first step, ahead of arbitration or the courts, per the platform&apos;s Terms &amp; Conditions. Separately, Community Feedback is the place for general suggestions, complaints, or praise about the platform itself, not tied to a specific transaction.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">13. Notifications</h2>
      <p>The notification bell keeps you updated in real time — a new offer, an approval decision, a message, a wallet transfer received, and more. From your Profile page, you can control which categories you receive: offers, messages, and marketing/promotional notifications each have their own real on/off toggle.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">14. Account Settings</h2>
      <ul className="list-disc pl-5 space-y-1 mb-2">
        <li>Notification preferences — control offers, messages, and marketing notifications independently</li>
        <li>Diaspora Mode — a setting for CHS users managing property or transactions from outside Nigeria</li>
        <li>Biometric login — set up or remove Face ID / fingerprint login for this device</li>
        <li>Linked bank account — view your one linked account; changing it goes through a real approval flow</li>
      </ul>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">15. Market Data</h2>
      <p>From the bottom navigation, &quot;Average property prices&quot; and &quot;Property demand trend&quot; show real, genuine market data — actual current listing prices and demand patterns, not estimated or placeholder figures.</p>
      <div className="border-t border-gray-200 my-3" />
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">16. For the CHS Admin Team</h2>
      <p>This section is written for CHS staff operating the platform, not for the general public.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.1 Super Admin</h3>
      <p>There is one real Super Admin account, practically involved in every part of the platform. The Super Admin handles Finance and Engagement (Engage CHS requests) directly, and is the one who reviews and ratifies every high-stakes decision made by a sub-admin before it actually takes effect.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.2 Sub-admin roles</h3>
      <p>Every other admin is assigned to exactly one of five real domains by the Super Admin, and can only ever see and act within that domain:</p>
      <ul className="list-disc pl-5 space-y-1 mb-2">
        <li>Customer Care — disputes, community feedback</li>
        <li>Registration &amp; Setup — new account approvals, face/liveness verification</li>
        <li>Owner/Buyer/Tenant — property verification, rental applications, sale approvals, inspections, concierge requests</li>
        <li>Agent Relations — referral fee tracking</li>
        <li>Artisan/Developer/PM/Vendor — artisan, vendor, and developer verification, maintenance routing</li>
      </ul>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.3 The approval queue — how sign-off works</h3>
      <p>Routine actions (like moving a fault report forward, or triaging feedback) happen immediately. High-stakes actions — anything financial, and every verification decision — do not take effect the moment a sub-admin submits them. They&apos;re held in a real pending queue until the Super Admin actually approves or rejects it; only then does the real change apply and the affected user get notified. A sub-admin can only ever submit a request within their own assigned domain — attempting anything outside it is blocked outright.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.4 Logging in as an admin</h3>
      <p>A sub-admin&apos;s password alone isn&apos;t enough to reach the dashboard. After a correct password, a real approval code is generated and sent directly to the Super Admin, who must approve the specific login attempt before it goes through — closing the gap a simple accept/reject tap would leave open.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.5 Assigning a sub-admin role</h3>
      <p>From the Super Admin&apos;s Overview tab, use &quot;Assign an admin role&quot; — enter the person&apos;s existing phone number or email (they must already have a real CHS account) and select their domain. This promotes their existing account; it does not create a brand-new one.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.6 Trace an Account — resolving a real support issue</h3>
      <p>Search by phone, email, or name to find a real person, then see everything real about them in one place: wallet balance and full transaction history, promotion credit history and every active or past promotion, every construction roadmap unlock, their linked bank account, and every Engage CHS request. This is the real tool for resolving a complaint like &quot;I paid but nothing happened&quot; — the same way a phone network&apos;s support line traces an issue the moment you give them your number. Super Admin only, since it surfaces real financial data across every system.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.7 Sub-admin action history</h3>
      <p>Once a sub-admin&apos;s request is approved or rejected, it doesn&apos;t just disappear — &quot;View sub-admin action history&quot; on the Overview tab shows a real, permanent record of every past decision, who made it, and any note attached.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.8 Mortgage (Rent to Own) desk</h3>
      <p>Under Rent-to-Own, admin sees every agreement, newest first, and nothing ever drops out of the list. Admin relays each new request to the owner, passes the owner&apos;s answer to the buyer, releases each installment held for the owner (one by one, or &quot;Release all&quot;), checks the owner&apos;s uploaded documents (approve, or ask for changes), and watches the hard copy handover. The FINAL release is always done by hand by a super admin: a sub-admin sees a notice instead of the button. If the owner has shown no proof and the buyer has not confirmed, a note of at least ten characters saying how you verified the handover is required.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">16.9 The auto-release tick box</h3>
      <p>At the top of the Rent-to-Own desk there is a box, &quot;Auto release of final mortgage payments.&quot; It is OFF unless a super admin ticks it, and every change is recorded in the audit log. When it is OFF, every final payment waits for a super admin. When it is ticked, the final payment is released the moment the buyer confirms receipt. It exists for busy periods, when many final payments are due at once; untick it afterwards. A super admin can also reverse a final release that should not have happened, which returns the money to CHS hold and records the reversal.</p>
      <div className="border-t border-gray-200 my-3" />
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">17. Rent to Own / Mortgage</h2>
      <p>Some properties are listed under Rent to Own / Mortgage instead of a straight sale — a real way to progressively own a property through monthly installments rather than one lump-sum payment.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">17.1 As a buyer</h3>
      <p>On a Rent to Own listing, tap &quot;Request Rent to Own / Mortgage.&quot; First give CHS your details (full name, phone, occupation, source of funds, address). The request goes to CHS, which passes it to the owner. When the owner answers, CHS tells you. Once your agreement starts, you can pay one instalment or any larger amount, up to the whole balance, from your Wallet. Every payment goes to CHS first and is released to the owner by CHS, and your ownership percentage grows with every payment. The owner never sees your phone number, and you never deal with the owner directly.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">17.1.1 Getting your documents</h3>
      <p>When you have paid in full, the final payment stays with CHS until the property documents are in your hands. Tap &quot;Request my documents,&quot; say who should receive them, where, your phone number and how you prefer them delivered. The owner uploads the documents for CHS to check, and once CHS approves them you can read the soft copy in the app. The owner then sends the hard copies. When they arrive, tap &quot;I have received my documents.&quot; CHS then releases the final payment to the owner by hand. Only then is the agreement completed.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">17.2 As a seller</h3>
      <p>When listing under this category, set your real total price, real monthly installment amount, and the real term in years. A buyer&apos;s request reaches CHS first, then your Owner dashboard, where you approve or decline it (a decline needs a short reason with no contact details). You see the buyer only as a first name and initial, for example &quot;Alex P.&quot;, with a CHS reference. Each installment is held by CHS and released to your wallet by CHS. Your final payment is held until the documents are handed over: when the buyer asks for them, upload them for CHS to check, wait for CHS&apos;s approval, send the hard copies, and add a courier receipt or proof. After the buyer confirms receipt, CHS releases your final payment by hand. CHS never gives you the buyer&apos;s phone number.</p>

      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">18. Estate Management (Property Managers)</h2>
      <p>If you manage a real, bounded estate of many housing units, CHS&apos;s Estate Management tools let you run the whole estate from one dashboard rather than juggling individual properties.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">18.1 Setting up your estate</h3>
      <p>From Manager → My Estates, create a real estate with its name, address, and planned unit count. Subscribe to unlock it — real monthly pricing scales with how many units you manage, and gets cheaper per unit as your estate grows.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">18.2 Adding units</h3>
      <p>Upload a real CSV file to add many units at once, instead of one at a time — the real answer to onboarding an estate with hundreds of housing units.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">18.3 Your real dashboard</h3>
      <p>See real, live occupancy, open disputes, pending maintenance, and service charge collection across your entire estate in one place — no need to check each property separately.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">18.4 Service charges</h3>
      <p>Bill every real occupied unit at once for a genuine service charge (security, common area maintenance) — this is entirely separate from rent, and vacant units are automatically skipped.</p>

      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">19. Host and Guest (Shortlet &amp; Hire)</h2>
      <p>Host and Guest are real, separate roles from Owner and Buyer, each with their own dashboard — add either one from Profile → Add another role, without needing to log out.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.1 Requesting a booking (Guest)</h3>
      <p>Choose your dates on a Shortlet or Hire listing and you&apos;ll see the real, full price before committing — the nightly rate plus CHS&apos;s commission, and a refundable security deposit if the host requires one for first-time guests. If the property has real house rules on file, you&apos;ll need to read and check a box agreeing to them before you can request to book. Requesting a booking places the full amount on hold — it is not an instant confirmation. The host must genuinely accept before your stay is confirmed; if they decline, you are automatically and fully refunded.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.2 Accepting or declining a request (Host)</h3>
      <p>From your Host dashboard, review each real booking request — including the guest&apos;s uploaded ID — and accept or decline with an optional note. Accepting confirms the stay; declining triggers an automatic, full refund to the guest.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.3 Getting paid (Host)</h3>
      <p>As soon as your guest arrives and confirms everything is as described (or automatically 24 hours after check-in if they do not respond), CHS releases your real net payout (the rent, minus your own commission) to your wallet. If you require a security deposit and it&apos;s genuinely needed, CHS resolves it directly with you after the stay — releasing it back to the guest, or paying it to you if real damage is confirmed.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.4 Cancelling a booking (Guest)</h3>
      <p>You can cancel a pending or confirmed booking at any time before check-in. Cancelling 48 or more hours before check-in gets you a full refund; within 48 hours, a 50% refund; on or after check-in, no refund.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.5 Ratings and disputes</h3>
      <p>After a confirmed stay, host and guest can each rate the other once. If something genuinely goes wrong, either side can raise a real dispute directly from their dashboard for CHS to review.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.6 If a host cancels (Host)</h3>
      <p>A host who cancels a confirmed booking that has not started must give a reason of at least ten characters, with no contact details. The guest is refunded in full and the dates stay blocked. The first time in 90 days is a warning. The second time costs a penalty of 10% of the booking value, which CHS collects from later payouts. A third time suspends the listing for review. CHS helps the guest find another place.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.7 Digital check-in (Guest and Host)</h3>
      <p>When a booking is confirmed the guest receives an arrival pass with a code. Before arrival the guest completes a short registration card; on the day, tapping &quot;I have arrived&quot; (checked against the hotel&apos;s location when it is set) shows the lockbox code if the host uses one. The front desk (the host, or staff the host adds by phone number) sees an arrivals board, verifies the pass and checks the guest in. If a guest does not show up by noon the day after check-in, the host can mark a no-show: the host is paid under the cancellation terms, the deposit goes back to the guest and the room is freed.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">19.8 Hotel operations (Host and staff)</h3>
      <p>Each hotel or lodge listing on the host dashboard has a &quot;Hotel operations&quot; panel with three tabs. Housekeeping shows every room as occupied, to clean, ready, inspected or out of order; a room appears as to-clean by itself once its guest has left, and staff tap Cleaned, Inspected or Out of order. Repairs lets staff log a fault against a room with a priority (an urgent one alerts the owner), then move it to in progress and done with its cost. Money lets staff record income from the restaurant, bar, laundry, gym and events; the owner alone records expenses, voids a wrong entry (it stays visible, struck through, with the reason), and sees the report and ledger for any date range: occupancy, average room rate, revenue per available room, income, expenses and net result, with a CSV download. Every entry records who made it and the exact date and time. Guests get a welcome at check-in and a thank-you after check-out, and the owner gets one evening summary.</p>

      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">19A. Event services for an event centre</h2>
      <p>When you request an event centre, choose your capacity and date, tick any priced facilities the venue lists, and then use &quot;Services you would like arranged&quot; to ask for ushers (and how many), a caterer, a live band, security personnel (and how many), or write anything else you need, such as an MC, DJ, photographer or decoration. Your request goes to CHS, then to the venue, who confirms or declines. Nothing is charged until the venue confirms, and you then have a short time to pay from your wallet.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">19B. Hospitality Suite: team, plans, import and calendar sync (Host)</h2>
      <p><strong className="text-chs-charcoal">Team and roles.</strong> On the host dashboard, &quot;My team&quot; adds staff by the phone number on their CHS account. Roles are Manager, Front desk, Housekeeping, Kitchen/bar and Accountant, and each person can be limited to chosen properties. They open <em>Work</em> to see their duties and send shift reports. The owner or a manager assigns duties with a priority and a due time; the person is notified, marks the duty done with an optional note, and the assigner is told. Every duty, completion and report carries the person&apos;s name and the exact date and time.</p>
      <p><strong className="text-chs-charcoal">Plans.</strong> &quot;Plans&quot; on the host dashboard shows Listed (free), Pro and Business. A paid plan is paid from your wallet for 30 days and renews from the wallet until you cancel; if a renewal fails you have 7 days to top up, then you move to Listed and your records stay readable. A paid plan also lowers the CHS commission on bookings CHS brings you. CHS may run a free pilot for chosen hosts. While the master switch is off, every host can use every tool.</p>
      <p><strong className="text-chs-charcoal">Import and calendar sync.</strong> In Hotel operations, the Import &amp; sync tab reads an Excel (.xlsx) or CSV sheet of rooms and prices, income or expenses. It matches your columns, shows a preview and saves nothing until you confirm; an import can be undone. You can also copy a private calendar link for each room into Booking.com, Airbnb or Google Calendar, and paste their calendar links into CHS so dates booked elsewhere are blocked here. Tap Sync now to refresh a linked calendar. Dates that clash with an existing booking are not added and are reported to you.</p>

      <p><strong className="text-chs-charcoal">Event day control (event centres).</strong> Under &quot;Event day control&quot; each paid, confirmed event shows what the client asked for (ushers, caterer, live band, security, notes). The owner or a manager records who is providing each service; confirming a vendor tells the client its name, never its phone number. &quot;Create the run sheet&quot; builds a checklist from what the client asked for (set-up, sound check, caterer, band, ushers, security, clear-up, lock-up). Team members tick tasks, and each tick records who did it and when; the owner or a manager can add tasks, give them to a person, or skip them.</p>

            <p><strong className="text-chs-charcoal">Menu, sales, stock and assets.</strong> In Hotel operations, the Menu &amp; stock tab holds your digital menu, a quick sales screen for the restaurant or bar, your stock list with reorder levels, recipes (how much stock one portion uses) and an asset register with each item&apos;s condition history. A guest who has been checked in sees your menu on their booking and can order to their room; you move the order to preparing and delivered, then record how they paid. Paid orders and counter sales go into your income by department, and stock falls automatically when an order is delivered. Guests pay the hotel directly: CHS does not hold or take a commission on this money. Owners and managers edit the menu and assets; other staff can take orders, record sales and update stock.</p>
      <p><strong className="text-chs-charcoal">Event quotations.</strong> For an event, the owner or a manager can send a quotation for extra services (ushers, catering, decoration and so on) from Event day control, with a payment schedule whose dates fall on or before the event. The client sees it on their booking and accepts or declines before it expires. These amounts are paid to the venue directly and are separate from the CHS booking payment; the venue records each payment as received, which adds it to the venue&apos;s income. CHS does not hold or take a commission on these extras. A quotation with a payment recorded cannot be withdrawn or replaced.</p>
<h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">20. Commercial Developer</h2>
      <p>A Commercial Developer has a real, dedicated dashboard showing your application status (company details, CAC number, whether you offer instalment plans or accept investment capital, and your portfolio link) alongside every real property or development you&apos;ve listed.</p>

      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">21. Agent &amp; Manager Business Tools</h2>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">21.1 Managing your own team</h3>
      <p>Invite genuine, separate staff accounts to work under you, assign each a role label, and see their real daily activity reports. The first 2 staff members are free; adding a 3rd requires a real subscription, tiered by how many staff you have, with a discount for longer commitments (6 months paid returns 8 real months of access; 12 months paid returns 18).</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">21.2 Registers, expenses, and receipts</h3>
      <p>A real tenant register and a real property/owner register, both searchable and with actual ID documents attached — plus expense/income tracking, a remittance flow for paying collected rent to the real owner, and auto-generated digital receipts for completed transactions.</p>

      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">22. Account Security</h2>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">22.1 Resetting a forgotten PIN</h3>
      <p>From the login screen, tap &quot;Forgot your PIN?&quot; and verify your identity using the real phone number and NIN you registered with — then set a brand new PIN immediately. No email or SMS code is used for this.</p>
      <h3 className="text-sm font-bold text-chs-charcoal mt-3 mb-1">22.2 Closing your account</h3>
      <p>From your Profile page, you can deactivate your account at any time. This genuinely hides your account and listings from CHS immediately — nothing is deleted, and simply logging back in reactivates it.</p>

      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">23. Notifications and Lists</h2>
      <p>Every dashboard (Buyer, Tenant, Owner, Host, Agent, Manager, Vendor, Admin and the rest) has its own notification bell. Tapping a notification opens the exact page and item it is about. Every recorded event (a document sent or received, a confirmation, a notification, a payment, an application) shows its full date and time, down to the second, in Nigerian time (WAT), so CHS and both sides always have a defensible record of exactly when something happened. Lists everywhere show the newest first, with the exceptions of upcoming due dates and scheduled inspection dates, which are listed soonest first.</p>
      <h2 className="font-serif text-lg font-bold text-chs-charcoal mt-5 mb-2">24. Getting Help</h2>
      <p>If something in the app doesn&apos;t behave the way this guide describes, or you&apos;re stuck on something not covered here, use &quot;Property request&quot; / &quot;Talk to an Agent&quot; to reach the CHS team directly, or Community Feedback to flag a general platform issue. For anything urgent involving an active transaction or payment, contact CHS support directly rather than waiting.</p>
      <p>This guide reflects the CHS platform as it stands today, including every feature described above. As new features are added, this guide should be updated alongside them — the same discipline applied to the platform&apos;s Terms &amp; Conditions.</p>
    </div>
  );
}