export const FEATURE_CATALOG: { title: string; rows: { feature: string; how: string; destination: string; admin: string }[] }[] = [
  {
    title: "1. Platform-Wide (Every Role)",
    rows: [
      { feature: "Registration with role selection", how: "Buyer, Tenant, Property Owner, Agent, Property Manager, or Commercial Developer — with role-specific extra fields (e.g. professional certificate upload for Managers).", destination: "Register page", admin: "New accounts land in Admin → Registrations, pending approval" },
      { feature: "NIN uniqueness check", how: "A real National Identification Number can only ever be tied to one CHS account.", destination: "Register page", admin: "N/A — enforced at registration" },
      { feature: "Multi-role linking", how: "One real identity, one wallet, one login can hold several roles at once (e.g. Owner + Tenant) via \"Link Account\" rather than a second registration.", destination: "Link Account page — every role", admin: "N/A — self-service" },
      { feature: "Biometric login (Face ID / fingerprint)", how: "Real WebAuthn — uses the device's own secure hardware; CHS never sees or stores the actual biometric data.", destination: "Login page + Profile setup — every role", admin: "N/A — self-service" },
      { feature: "Valid ID + liveness verification", how: "Real document upload plus a genuine, real-time photo capture (never an uploaded photo) reviewed by CHS staff.", destination: "Registration / Profile — every role", admin: "Admin → Face Verification (Registration & Setup domain)" },
      { feature: "Editable profile with re-verification trigger", how: "Name, phone, address, and state are genuinely editable. A real name change automatically resets ID/liveness verification.", destination: "Profile page — every role", admin: "Real notification to Super Admin on any name change" },
      { feature: "Wallet (main + rent savings + maintenance reserve)", how: "Three real sub-balances per user — a main spending balance plus two dedicated savings pots for rent renewal and maintenance costs.", destination: "Wallet page — every role", admin: "Admin → Finance — search any user's real balances, freeze/unfreeze" },
      { feature: "Wallet funding via Paystack", how: "Real, secure card/bank/USSD payment; balance updates automatically once payment genuinely completes.", destination: "Wallet page — every role", admin: "N/A — self-service" },
      { feature: "Wallet withdrawal to bank", how: "Only one linked bank account per wallet, for security. Real Paystack transfer to the verified account.", destination: "Wallet page — every role", admin: "N/A — self-service, admin sees real withdrawal_requests records" },
      { feature: "Wallet-to-wallet transfer", how: "Send funds directly to another CHS user by phone or email — real-time lookup and instant transfer.", destination: "Wallet page — every role", admin: "N/A — self-service" },
      { feature: "Bank account linking with real-time verification", how: "200+ real Nigerian banks with search; the account number is checked against the real bank network before it can ever be linked. Real 48-hour security window on any change.", destination: "Wallet → Link bank account — every role", admin: "N/A — self-service, real-time" },
      { feature: "Notification preferences", how: "Independent real toggles for offers, messages, and marketing notifications.", destination: "Profile page — every role", admin: "N/A — self-service" },
      { feature: "Diaspora Mode", how: "A real setting for CHS users managing property or transactions from outside Nigeria.", destination: "Profile page — every role", admin: "N/A — self-service" },
      { feature: "Terms & Conditions scroll-to-accept gate", how: "A real, meaningful acceptance — the checkbox only unlocks after genuinely scrolling to the bottom. Required before any dashboard is reachable.", destination: "First login — every role", admin: "N/A — one-time gate" },
      { feature: "Role-specific first-dashboard guide + persistent Users Guide", how: "A short popup on first dashboard visit, plus a full, always-accessible reference page.", destination: "First login popup + More menu → Users Guide", admin: "N/A — reference" },
      { feature: "Dark mode", how: "A real, complete theme system across the whole app, with an app-wide fix ensuring form text stays readable in both modes.", destination: "Every page — every role", admin: "N/A — visual" },
      { feature: "PWA install + splash screen", how: "Installable as a real app on the home screen, with a proper full-screen splash and app icon.", destination: "Browser install prompt", admin: "N/A — visual" },
    ],
  },
  {
    title: "2. Buyer & Tenant",
    rows: [
      { feature: "Location + price search", how: "Filter by state, LGA, area, property type, minimum bedrooms, and a real minimum/maximum price range.", destination: "Homepage search — Buyer / Tenant", admin: "N/A — self-service" },
      { feature: "Rent / Sale / Shortlet tabs", how: "Real filtering of the whole catalog by purpose.", destination: "Homepage — Buyer / Tenant", admin: "N/A" },
      { feature: "Saved Properties & Saved Searches", how: "Save individual listings, or save a whole search to be matched automatically as new listings arrive.", destination: "Saved page — Buyer / Tenant", admin: "N/A — self-service" },
      { feature: "Making an offer (sale)", how: "Propose a real price directly to the owner; goes through a real CHS Sale Approvals checkpoint before anything moves to escrow.", destination: "Property detail page — Buyer", admin: "Admin → Sale Approvals (Owner/Buyer/Tenant domain)" },
      { feature: "Rental application", how: "A real application, screened by CHS staff before the owner ever sees it.", destination: "Property detail page — Tenant", admin: "Admin → Applications (Owner/Buyer/Tenant domain)" },
      { feature: "Inspection booking + transport fee", how: "Real fee calculated per-person based on distance; a genuine 12-hour minimum notice enforced by the database itself.", destination: "Property detail page — Buyer / Tenant", admin: "Admin → Inspections (Owner/Buyer/Tenant domain)" },
      { feature: "Buyer/Tenant Readiness Score", how: "A real questionnaire (timeline, funds ready, decision-maker) plus verification and inspection-attendance history — shown to owners, never a fee or gate.", destination: "Inspection booking form — Buyer / Tenant", admin: "N/A — computed live" },
      { feature: "Shortlet booking", how: "Paid instantly through the wallet, held in real escrow until check-in is confirmed. Real guest verification required.", destination: "Property detail page — Buyer / Tenant", admin: "N/A — self-service" },
      { feature: "Rent-to-Own", how: "Where offered, a real monthly amount counting toward eventual ownership, shown directly on the listing.", destination: "Property detail page — Buyer", admin: "N/A — set by owner at listing time" },
      { feature: "House Rules acknowledgment", how: "A real, documented agreement a tenant acknowledges as part of their tenancy.", destination: "Tenant dashboard, per tenancy", admin: "N/A — set by owner" },
      { feature: "Property Condition Report", how: "Documented and photographed at move-in — real evidence-based liability instead of a caution-fee guess.", destination: "Condition Report page — Tenant", admin: "N/A — self-service" },
      { feature: "Formal Notices", how: "Real formal communications (e.g. rent reminders, lease notices) from owner/CHS, viewable and expandable.", destination: "Tenant dashboard", admin: "N/A — sent by owner/CHS" },
      { feature: "Owner–tenant message thread", how: "A real, direct messaging channel per tenancy.", destination: "Tenant dashboard, per tenancy", admin: "N/A — self-service" },
      { feature: "Raise a Dispute", how: "A real, two-sided dispute process — CHS's internal resolution is the first step before arbitration or courts.", destination: "Tenant dashboard + Owner dashboard", admin: "Admin → Disputes (Customer Care domain)" },
      { feature: "Talk to an Agent (Concierge)", how: "Describe a property need in free text or voice instead of using search filters — a real request CHS follows up on personally.", destination: "Bottom nav → Property request — Buyer / Tenant", admin: "Admin → Concierge, within Owner/Buyer/Tenant domain" },
      { feature: "Urgent & Emergency Sale browsing", how: "Real, discounted, time-boxed listings shown in a dedicated homepage row with the real deadline.", destination: "Homepage — Buyer", admin: "N/A — browsing only" },
      { feature: "Market data (average prices, demand trend)", how: "Real, genuine data (not placeholder figures) on current prices and search-driven demand patterns.", destination: "Bottom nav → Average prices / Demand trend", admin: "N/A — self-service" },
      { feature: "Engage CHS — buy a construction project", how: "Full request flow with real specifications, document checklist, two-way chat, and the Construction Roadmap tool.", destination: "Engage CHS page — Buyer / Owner", admin: "Admin → Engage CHS (Super Admin only)" },
    ],
  },
  {
    title: "3. Property Owner",
    rows: [
      { feature: "List a property", how: "Photos, location, price, purpose, bedrooms, and special terms (rent-to-own, house rules). Starts unverified.", destination: "Owner dashboard → List a property", admin: "Admin → Properties (Owner/Buyer/Tenant domain)" },
      { feature: "Property verification", how: "CHS reviews every listing before it's publicly visible — the real meaning behind \"CHS Verified.\"", destination: "Owner dashboard", admin: "Admin → Properties (Owner/Buyer/Tenant domain)" },
      { feature: "Fixed-tier promotion (7/30/90-Day Boost)", how: "One-off paid tier, debited directly from the wallet.", destination: "Promote page, per listing", admin: "N/A — self-service" },
      { feature: "Credit-based promotion (pause anytime)", how: "Real, shared credit balance across every listing; each listing charged separately per real day it's on, based on real location/size cost. Real ranking (Category A–D + literal Top 10/20 position) against the same real local market.", destination: "Promote page, per listing", admin: "N/A — automatic, database-driven" },
      { feature: "Urgent & Emergency Sale activation", how: "Requires the listing already verified and owner ID-verified. Real original price, discount, and deadline shown to buyers.", destination: "Owner dashboard → 🚨 Urgent Sale", admin: "Notified via general notifications on activation" },
      { feature: "Managing offers & rental applications", how: "Real accept/reject decisions on real, CHS-screened offers and applications.", destination: "Owner dashboard", admin: "Admin → Sale Approvals / Applications" },
      { feature: "Inspection management + Readiness Score visibility", how: "See each real requester's readiness score; mark real attendance/no-show after the scheduled time passes.", destination: "Owner dashboard, per property", admin: "Admin → Inspections" },
      { feature: "Delegating to a Property Manager", how: "Hands maintenance and certain approvals to a registered Manager; reversible any time.", destination: "Owner dashboard", admin: "N/A — self-service" },
      { feature: "Property analytics", how: "Real view counts, inspection counts, and interest counts — not fixed placeholder numbers.", destination: "Analytics page, per listing", admin: "N/A — self-service" },
      { feature: "Editing a live listing", how: "Real edits to an already-published property.", destination: "Edit listing page", admin: "N/A — self-service" },
      { feature: "Engage CHS for a professional service", how: "Full Property Management, Sale Negotiation, Construction Monitoring, Project Management, Renovation — each with its own real terms and fee schedule.", destination: "Engage CHS page — Owner", admin: "Admin → Engage CHS (Super Admin only)" },
    ],
  },
  {
    title: "4. Agent",
    rows: [
      { feature: "Unique referral link", how: "A real code (e.g. CHS-AG-0024) automatically attached to every property link generated — always opens the property directly on CHS.", destination: "Agent dashboard", admin: "N/A — self-service" },
      { feature: "Automatic commission attribution", how: "If a referred visitor completes a real transaction on that property, CHS automatically attributes and credits the commission.", destination: "Agent dashboard", admin: "Admin → Referral fees (Agent Relations domain)" },
      { feature: "Real referral tracking (masked for privacy)", how: "Real deal stage, earnings this month, and total earned — served from a privacy-conscious masked view.", destination: "Agent dashboard", admin: "Admin → Referral fees" },
    ],
  },
  {
    title: "5. Property Manager",
    rows: [
      { feature: "Delegated property management", how: "Owners can delegate specific properties; maintenance and certain approvals route to the manager directly.", destination: "Manager dashboard", admin: "N/A — self-service" },
      { feature: "Management termination", how: "An owner can reverse delegation any time, handing responsibilities back.", destination: "Owner dashboard (trigger) / Manager dashboard (effect)", admin: "N/A — self-service" },
      { feature: "Posting a maintenance job for quotation", how: "Real job posts that verified artisans can quote on, ranked by a transparent rating/reliability/experience/equipment formula.", destination: "Manager dashboard", admin: "Admin → Maintenance (Artisan/Developer/PM/Vendor domain)" },
      { feature: "Rating an artisan", how: "Real, genuine ratings after a completed job.", destination: "Manager dashboard, per completed job", admin: "N/A — self-service" },
    ],
  },
  {
    title: "6. Commercial Developer",
    rows: [
      { feature: "Developer registration & review", how: "A real application reviewed by CHS before projects go live.", destination: "Register / Developer dashboard", admin: "Admin → Developers (Artisan/Developer/PM/Vendor domain)" },
      { feature: "Listing development projects", how: "Estates, instalment plans, and investment plans.", destination: "Developer dashboard", admin: "Admin → Developers" },
    ],
  },
  {
    title: "7. Vendor & Marketplace",
    rows: [
      { feature: "Vendor registration & verification", how: "Reviewed by CHS before listings go live — the same trust standard applied platform-wide.", destination: "Become a Vendor / Vendor dashboard", admin: "Admin → Vendors (Artisan/Developer/PM/Vendor domain)" },
      { feature: "Listing products & bundles", how: "Real materials/services catalog, browsable by category on the Marketplace.", destination: "Vendor dashboard (list) + Marketplace page (browse)", admin: "N/A — self-service" },
      { feature: "Service quote requests", how: "Real incoming requests for a quote on a specific service.", destination: "Vendor dashboard", admin: "N/A — self-service" },
      { feature: "Referral fee tracking", how: "Real fees on deals connected through the Marketplace.", destination: "Vendor dashboard", admin: "Admin → Referral fees" },
    ],
  },
  {
    title: "8. Artisan",
    rows: [
      { feature: "Artisan registration & verification", how: "Real trades, years of experience, certification, and equipment tier (with photo/receipt backing) — reviewed before quoting is allowed.", destination: "Become an Artisan / Artisan dashboard", admin: "Admin → Artisans (Artisan/Developer/PM/Vendor domain)" },
      { feature: "Quoting on maintenance jobs", how: "Real quotes ranked by a transparent formula: rating/reliability first, experience second, equipment third.", destination: "Artisan dashboard", admin: "Admin → Maintenance" },
      { feature: "Full-management job priority", how: "For any property under full CHS management, maintenance work goes first and exclusively to verified CHS Maintenance Agents.", destination: "Automatic — Artisan", admin: "N/A — automatic" },
      { feature: "Job dispute resolution", how: "Either the artisan or the client can raise a genuine, two-sided dispute about a completed job.", destination: "Artisan dashboard", admin: "Admin → Disputes" },
      { feature: "Ratings received", how: "Real, visible rating history.", destination: "Artisan dashboard", admin: "N/A — self-service" },
    ],
  },
  {
    title: "9. Admin & Platform Management",
    rows: [
      { feature: "Super Admin role", how: "One real account, practically involved in every part of the platform — handles Finance and Engage CHS directly, and ratifies every sub-admin's high-stakes decision.", destination: "Admin dashboard", admin: "Admin → Overview" },
      { feature: "Five real sub-admin domains", how: "Customer Care, Registration & Setup, Owner/Buyer/Tenant, Agent Relations, Artisan/Developer/PM/Vendor — each sub-admin only sees and acts within their own domain, enforced at the database level.", destination: "Admin dashboard, tab-gated per domain", admin: "Admin → Overview → Assign an admin role" },
      { feature: "Code-based admin login approval", how: "A sub-admin's correct password alone isn't enough — a real code is generated and sent to the Super Admin, who must approve that specific login.", destination: "Sub-admin login flow", admin: "Admin → Overview — pending login approvals" },
      { feature: "High-stakes approval queue", how: "Routine sub-admin actions apply immediately; financial and verification decisions are held pending real Super Admin sign-off.", destination: "Admin dashboard, across relevant tabs", admin: "Admin → Overview — pending sub-admin actions" },
      { feature: "Trace an Account", how: "Search any real user by phone/email/name and see their full wallet balance + transaction history, promotion credits + active promotions, construction roadmap unlocks, linked bank account, and Engage CHS requests — all in one place. The real fix for resolving a support issue (\"I paid but nothing happened\") the way a phone network traces an account from just a phone number.", destination: "N/A — admin only", admin: "Admin → 🔎 Trace an Account (Super Admin only)" },
      { feature: "Sub-admin action history", how: "A real, permanent audit log of every resolved sub-admin request — previously, once approved or rejected, a request simply vanished with no record.", destination: "N/A — admin only", admin: "Admin → Overview → View sub-admin action history" },
      { feature: "Pre-launch admin test mode", how: "Super Admin can preview any real dashboard using their own account, never a real user's data, with a visible banner the whole time.", destination: "N/A — testing tool", admin: "Admin → Overview → Switch role for testing" },
      { feature: "Finance", how: "Search any real user's wallet, view all three real balances, freeze/unfreeze.", destination: "N/A — admin only", admin: "Admin → Finance" },
      { feature: "Sale Approvals", how: "The real checkpoint between an accepted offer and money moving to escrow.", destination: "N/A — admin only", admin: "Admin → Sale Approvals" },
      { feature: "Face Verification (Liveness)", how: "Real human review of each real-time capture.", destination: "N/A — admin only", admin: "Admin → Face Verification" },
      { feature: "Registrations", how: "Approve or reject new real accounts.", destination: "N/A — admin only", admin: "Admin → Registrations" },
      { feature: "Applications", how: "Real rental application review before an owner ever sees it.", destination: "N/A — admin only", admin: "Admin → Applications" },
      { feature: "Properties", how: "Real listing verification before it's publicly visible.", destination: "N/A — admin only", admin: "Admin → Properties" },
      { feature: "Disputes", how: "Real, two-sided dispute resolution across tenancies and artisan jobs.", destination: "N/A — admin only", admin: "Admin → Disputes" },
      { feature: "Feedback", how: "General platform suggestions/complaints, not tied to a specific transaction.", destination: "N/A — admin only", admin: "Admin → Feedback" },
      { feature: "Engage CHS", how: "Real professional-service requests: specifications, document checklist, two-way chat, roadmap access — Super Admin only, per direct instruction.", destination: "N/A — admin only", admin: "Admin → Engage CHS" },
      { feature: "Vendors", how: "Real marketplace vendor verification.", destination: "N/A — admin only", admin: "Admin → Vendors" },
      { feature: "Referral fees", how: "Real agent/vendor commission tracking and payout, routed through the approval queue.", destination: "N/A — admin only", admin: "Admin → Referral fees" },
      { feature: "Maintenance", how: "Real fault report routing to the right artisan/manager.", destination: "N/A — admin only", admin: "Admin → Maintenance" },
      { feature: "Artisans", how: "Real trade/equipment verification before an artisan can quote.", destination: "N/A — admin only", admin: "Admin → Artisans" },
      { feature: "Inspections", how: "Real upcoming inspection oversight across the whole platform.", destination: "N/A — admin only", admin: "Admin → Inspections" },
      { feature: "Developers", how: "Real developer application review.", destination: "N/A — admin only", admin: "Admin → Developers" },
    ],
  },
];