-- No SQL in this one. This was a frontend-only round: the reusable
-- FileUploadBox component (drag-and-drop, click-to-upload), the
-- PropertyTourModal/PropertyTourButton "Take a Tour" gallery, and the
-- real auto-scroll-to-next-step fix on RentalApplicationForm. See
-- components/FileUploadBox.tsx, components/PropertyTourModal.tsx,
-- components/PropertyTourButton.tsx, and the scroll-into-view effect
-- in components/RentalApplicationForm.tsx.
