-- No SQL. Frontend-only: rolled the FileUploadBox component (built in
-- 384) out to every remaining raw <input type="file"> across the app
-- — vendor, house rules, Engage CHS, hire/shortlet bookings,
-- link-account, agent tenant registration, registration, become an
-- artisan, and the full list-property form (including the labeled
-- photo-slot grid).
